# Site settings
title: Sytac DevJam
email: devjam@sytac.nl
meetupurl: http://www.meetup.com/Sytac-Dev-Jam
description: > # this means to ignore newlines until "baseurl:"
  Monthly meetups for developers, brought to you with <3 by the fine people at Sytac.
baseurl: "/devjam" # the subpath of your site, e.g. /blog/
url: "http://devjam.sytac.nl" # the base hostname & protocol for your site
github_username:  sytac

# Build settings
markdown: kramdown
